services:
  cfw-proxy:
    environment:
      # ⚠️ Required:
      # Make sure change this to your host's public address
      - PROXY_USERNAME=awesome-username
      # ⚠️ Required:
      # You can use `openssl rand -base64 8` to generate a secure password
      - PROXY_PASSWORD=super-secret-password

      # Optional:
      - SHADOWSOCKS_CIPHER=AES-256-CFB
      - DNS=1.1.1.2, 1.0.0.2, 2606:4700:4700::1112, 2606:4700:4700::1112
      - MTU=1300

    image: ghcr.io/shahradelahi/cfw-proxy
    container_name: cfw-proxy
    restart: unless-stopped
    privileged: true
    volumes:
      - /lib/modules:/lib/modules
      - persist-data:/data
    ports:
      - "1080:1080"
      - "8080:8080"
      - "8338:8338"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  persist-data:
    driver: local
