#!/usr/bin/with-contenv bash
# shellcheck shell=bash

_USERNAME=${PROXY_USERNAME:-awesome-username}
_PASSWORD=${PROXY_PASSWORD:-super-secret-password}

lowercase() {
  echo "$1" | tr '[:upper:]' '[:lower:]'
}

export GOST_LOGGER_LEVEL=${GOST_LOGGER_LEVEL:-info}

gost \
  -L "socks5://${_USERNAME}:${_PASSWORD}@:${SOCKS5_PORT:-1080}" \
  -L "http://${_USERNAME}:${_PASSWORD}@:${HTTP_PORT:-8080}" \
  -L "ss://$(lowercase "${SHADOWSOCKS_CIPHER:-AES-256-CFB}"):${_PASSWORD}@:${SHADOWSOCKS_PORT:-8338}"
