#!/usr/bin/env sh

case "$(arch)" in
  x86_64 | amd64) _ARCH="amd64" ;;
  aarch64 | arm64) _ARCH="arm64" ;;
  armv7l | armv7) _ARCH="armv7" ;;
  mips64le) _ARCH="mips64le_softfloat" ;;
  386 | s390x)
    _ARCH="$TARGETARCH"
    ;;
  *)
    echo "Unsupported architecture. $(arch)"
    exit 1
    ;;
esac
DOWNLOAD_URL="https://github.com/ViRb3/wgcf/releases/download/v${WGCF_VERSION}/wgcf_${WGCF_VERSION}_linux_${_ARCH}"
wget -qO /usr/local/bin/wgcf "$DOWNLOAD_URL"
chmod +x /usr/local/bin/wgcf
