#!/bin/bash

register_wgcf_config() {
  wgcf register --accept-tos
  wgcf update
}

update_wgcf_config() {
  local IFACE=$(ip route show default | awk '{print $5}')
  local IPv4=$(ip addr show dev "$IFACE" | awk '/inet /{print $2}' | cut -d' ' -f2)
  local IPv6=$(ip addr show dev "$IFACE" | awk '/inet6 /{print $2}' | cut -d' ' -f2)
  local DIR="$(mktemp -d)"
  local DIST="${DIR}/wgcf-profile.conf"

  mv wgcf-profile.conf "$DIR"
  sed -i "/\[Interface\]/a PostDown = ip -6 rule delete from ${IPv6}  lookup main" "$DIST"
  sed -i "/\[Interface\]/a PostUp = ip -6 rule add from ${IPv6} lookup main" "$DIST"
  sed -i "/\[Interface\]/a PostDown = ip -4 rule delete from ${IPv4} lookup main" "$DIST"
  sed -i "/\[Interface\]/a PostUp = ip -4 rule add from ${IPv4} lookup main" "$DIST"

  mkdir -p "$(dirname "$1")"
  mv "$DIST" "$1"
}

install_wgcf() {
  case "$(arch)" in
    x86_64 | amd64) _ARCH="amd64" ;;
    aarch64 | arm64) _ARCH="arm64" ;;
    armv7l | armv7) _ARCH="armv7" ;;
    mips64le) _ARCH="mips64le_softfloat" ;;
    386 | s390x)
      _ARCH="$TARGETARCH"
      ;;
    *)
      echo "Unsupported architecture. $(arch)"
      exit 1
      ;;
  esac
  export DOWNLOAD_URL="https://github.com/ViRb3/wgcf/releases/download/v${WGCF_VERSION}/wgcf_${WGCF_VERSION}_linux_${_ARCH}"
  wget -qO /usr/local/bin/wgcf "$DOWNLOAD_URL"
  chmod +x /usr/local/bin/wgcf
}
